### ISSUE TITLE
Being contributor XD

### ISSUE THREAD

**Issue by Jolumine** [buc23/buc23.github.io#1]
ich bewerbe mich hiermit offiziell als Contributor für dieses Repo. 

Für Qualifikationen bitte ich sie sich mein Profil anzuschauen. 
Des weiteren stehe ich ihnen gerne für Fragen zur Verfügung. 

Mit freundlichen Grüßen 
Leonard Becker

**Comment by buc23** [comment]
![nicht anschauen](https://user-images.githubusercontent.com/125186452/218782879-1234b04d-a66c-4978-8230-ade7154d222a.gif)
